export enum StatusType {
  PENDING = "PENDING",
  IN_REVIEW = "IN_REVIEW",
  NEEDS_REVISION = "NEEDS_REVISION",
  REVISION_SUBMITTED = "REVISION_SUBMITTED",
  APPROVED = "APPROVED",
  REJECTED = "REJECTED",
  COMPLETED = "COMPLETED",
}
