export enum StatusType {
  PENDING = "PENDING",
  IN_REVIEW = "IN_REVIEW",
  NEEDS_REVISION = "NEEDS_REVISION",
  REVISION_SUBMITTED = "REVISION_SUBMITTED",
  APPROVED = "APPROVED",
  REJECTED = "REJECTED",
  COMPLETED = "COMPLETED",
}

export enum TagType {
  EDUCATION = "EDUCATION",
  TECHNOLOGY = "TECHNOLOGY",
  SCIENCE = "SCIENCE",
  HEALTH = "HEALTH",
  ART = "ART",
  HISTORY = "HISTORY",
  LITERATURE = "LITERATURE",
  BUSINESS = "BUSINESS",
  SPORTS = "SPORTS",
  ENVIRONMENT = "ENVIRONMENT",
  POLITICS = "POLITICS",
  CULTURE = "CULTURE",
  SOCIETY = "SOCIETY",
  ECONOMICS = "ECONOMICS",
  PHILOSOPHY = "PHILOSOPHY",
}

export enum SpecificationType {
  ENEM = "ENEM",
  VESTIBULAR = "VESTIBULAR",
  CONCURSO = "CONCURSO",
  ANPAD = "ANPAD",
  ANPEC = "ANPEC",
  OAB = "OAB",
  RESIDENCIA_MEDICA = "RESIDENCIA_MEDICA",
  TOEFL = "TOEFL",
  IELTS = "IELTS",
  SAT = "SAT",
  GMAT = "GMAT",
  GRE = "GRE",
  ESPECIFICO = "ESPECIFICO",
  OTHER = "OTHER",
}
